spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/java-23?serverTimezone=Asia/Seoul
    username: jus
    password: 1234
#  sql:
#    init:
#      mode: always
#  jpa:
#    hibernate:
#      ddl-auto: none